#!/usr/bin/env python3
"""Draws the project's artwork: assets/graceful-mark.svg and graceful-agility.svg.

Both are pixel art of one 32x32 sprite — a character mid-vault in the graceful
outfit — so the favicon and the banner are literally the same character. The
sprite is authored here rather than in the SVGs, because a grid of <rect>s is
not something anyone can edit by hand; change `sprite()` or `PALETTE` and
re-run:

    python3 tool/graceful_sprite.py

The palette is the default (pink) graceful recolour from Old School RuneScape,
matched by eye. No RuneScape asset is used — see assets/CREDITS.md.
"""

import os

N = 32  # the sprite grid is 32x32

PALETTE = {
    'o': '#22221f',  # outline
    'k': '#3f3f3d',  # charcoal: the eye band, the chest markings, gloves, boots
    'v': '#8e8a74',  # bone cloth in shadow: the cape, the back of the hood
                     # (darker than the reference, or the cape and the back
                     # leg merge into one pale mass at favicon sizes)
    'c': '#d8d3bd',  # bone cloth, the body of the outfit
    'w': '#ece8d8',  # bone cloth highlight
    'g': '#4fa79b',  # jade: the chest diamond and the waist sash
    'r': '#b03a2b',  # the red diamond, and the panel down the leg
    's': '#c18f66',  # skin, the only part of the wearer left uncovered
}
DISC = '#23262b'  # slate, dark enough for the bone cloth to carry the silhouette


def sprite():
    """The pose, painted back to front: cape, back limbs, torso, head, front."""
    g = [['.'] * N for _ in range(N)]
    dy = 1  # the pose is drawn one row high of the disc's centre

    def put(r, c, s):
        for i, ch in enumerate(s):
            if ch != ' ':
                g[r + dy][c + i] = ch

    # cape, trailing back from the shoulders
    put(12, 10, "oovvv")
    put(13, 8, "oovvvvvv")
    put(14, 6, "oovvvvvvv")
    put(15, 5, "ovvvvvvv")
    put(16, 4, "ovvvvvvv")
    put(17, 4, "ovvvvvv")
    put(18, 5, "ovvvvv")
    put(19, 6, "ovvv")
    # back arm: a bone pauldron, bare skin, a charcoal glove
    put(13, 11, "osssco")
    put(14, 8, "ossso")
    put(15, 7, "okko")
    # back leg, driving off
    put(19, 11, "occcco")
    put(20, 9, "occcco")
    put(21, 7, "occcco")
    put(22, 6, "occco")
    put(23, 4, "okkko")
    put(24, 4, "okkko")
    # torso: the charcoal markings, the jade and red diamonds, the jade sash
    put(12, 12, "oovccccco")
    put(13, 13, "ovckkcco")
    put(14, 13, "ovcgccwo")
    put(15, 13, "ovccrcwo")
    put(16, 14, "ovcccwo")
    put(17, 14, "oggggwo")
    put(18, 13, "ovcrccco")
    # hood: a long back, the charcoal eye band across the front
    put(4, 15, "ooooo")
    put(5, 12, "ooowcccco")
    put(6, 10, "oovwccccco")
    put(7, 10, "ovvwcckkko")
    put(8, 11, "ovvcckkkko")
    put(9, 13, "ovccccco")
    put(10, 15, "occcco")
    put(11, 14, "oovoccco")
    # front arm, reaching
    put(11, 21, "ooooo")
    put(12, 20, "ocssso")
    put(13, 23, "okko")
    # front leg: the red panel runs down it, into a charcoal boot
    put(19, 17, "occccco")
    put(20, 19, "ocrcco")
    put(21, 20, "ocrco")
    put(22, 20, "occco")
    put(23, 21, "occco")
    put(24, 21, "okko")
    put(25, 21, "okkkko")
    return [''.join(row) for row in g]


def rects(rows, indent):
    """One <rect> per run of equal pixels, rather than one per pixel."""
    out = []
    for y, row in enumerate(rows):
        x = 0
        while x < N:
            ch = row[x]
            if ch == '.':
                x += 1
                continue
            w = 1
            while x + w < N and row[x + w] == ch:
                w += 1
            out.append(f'{indent}<rect x="{x}" y="{y}" width="{w}" height="1" '
                       f'fill="{PALETTE[ch]}"/>')
            x += w
    return '\n'.join(out)


def legend(rows):
    """The grid, as a comment, so a diff of the artwork is readable."""
    key = '  '.join(f'{k} {v}' for k, v in PALETTE.items())
    body = '\n'.join('    ' + r for r in rows)
    return f'  <!-- Generated by tool/graceful_sprite.py — edit there, not here.\n' \
           f'    {key}\n\n{body}\n  -->'


def mark(rows):
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {N} {N}" width="{N}" height="{N}"
     shape-rendering="crispEdges" role="img" aria-label="Graceful Shell">
{legend(rows)}
  <circle cx="16" cy="16" r="15.5" fill="{DISC}"/>
{rects(rows, '  ')}
</svg>
'''


def banner(rows):
    """The sprite at 6x, vaulting the gap between two windows under a panel."""
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 960 420" width="960" height="420"
     shape-rendering="auto" role="img"
     aria-label="A hooded runner in the graceful outfit vaulting between two desktop windows, under a shell panel">
{legend(rows)}
  <defs>
    <linearGradient id="ga-sky" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="#232831"/>
      <stop offset="55%" stop-color="#1a1e25"/>
      <stop offset="1" stop-color="#121519"/>
    </linearGradient>
    <linearGradient id="ga-win" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#2c333c" stop-opacity=".95"/>
      <stop offset="1" stop-color="#1b2027" stop-opacity=".95"/>
    </linearGradient>
    <radialGradient id="ga-glow" cx="50%" cy="45%" r="55%">
      <stop offset="0" stop-color="#4fa79b" stop-opacity=".22"/>
      <stop offset="1" stop-color="#4fa79b" stop-opacity="0"/>
    </radialGradient>
  </defs>

  <rect width="960" height="420" fill="url(#ga-sky)"/>
  <rect width="960" height="420" fill="url(#ga-glow)"/>

  <!-- faint starfield -->
  <g fill="#dfe6e4" fill-opacity=".18">
    <circle cx="96" cy="72" r="1.6"/><circle cx="212" cy="46" r="1.1"/><circle cx="330" cy="96" r="1.4"/>
    <circle cx="628" cy="58" r="1.2"/><circle cx="742" cy="104" r="1.7"/><circle cx="884" cy="64" r="1.3"/>
    <circle cx="452" cy="40" r="1"/><circle cx="806" cy="176" r="1.2"/><circle cx="150" cy="168" r="1.1"/>
  </g>

  <!-- the shell's own panel, across the top -->
  <rect x="0" y="0" width="960" height="26" fill="#171b21" fill-opacity=".92"/>
  <g fill="#4fa79b" fill-opacity=".55">
    <rect x="24" y="10" width="26" height="6" rx="3"/>
    <rect x="58" y="10" width="12" height="6" rx="3" fill-opacity=".3"/>
    <rect x="78" y="10" width="12" height="6" rx="3" fill-opacity=".3"/>
    <rect x="432" y="10" width="52" height="6" rx="3" fill-opacity=".4"/>
    <rect x="806" y="10" width="18" height="6" rx="3"/>
    <rect x="832" y="10" width="18" height="6" rx="3"/>
    <rect x="858" y="10" width="42" height="6" rx="3"/>
  </g>
  <rect x="0" y="26" width="960" height="1" fill="#4fa79b" fill-opacity=".22"/>

  <!-- the obstacles: two windows with a gap between them -->
  <g>
    <rect x="70" y="248" width="290" height="140" rx="14" fill="url(#ga-win)"
          stroke="#4fa79b" stroke-opacity=".28" stroke-width="1.5"/>
    <rect x="70" y="248" width="290" height="30" rx="14" fill="#4fa79b" fill-opacity=".12"/>
    <rect x="70" y="264" width="290" height="14" fill="#4fa79b" fill-opacity=".12"/>
    <g fill="#7fc7bd" fill-opacity=".5">
      <circle cx="92" cy="263" r="4"/><circle cx="108" cy="263" r="4"/><circle cx="124" cy="263" r="4"/>
    </g>
    <g fill="#dfe6e4" fill-opacity=".13">
      <rect x="94" y="304" width="180" height="9" rx="4.5"/>
      <rect x="94" y="326" width="230" height="9" rx="4.5"/>
      <rect x="94" y="348" width="140" height="9" rx="4.5"/>
    </g>
  </g>
  <g>
    <rect x="600" y="292" width="290" height="106" rx="14" fill="url(#ga-win)"
          stroke="#4fa79b" stroke-opacity=".28" stroke-width="1.5"/>
    <rect x="600" y="292" width="290" height="30" rx="14" fill="#4fa79b" fill-opacity=".12"/>
    <rect x="600" y="308" width="290" height="14" fill="#4fa79b" fill-opacity=".12"/>
    <g fill="#7fc7bd" fill-opacity=".5">
      <circle cx="622" cy="307" r="4"/><circle cx="638" cy="307" r="4"/><circle cx="654" cy="307" r="4"/>
    </g>
    <g fill="#dfe6e4" fill-opacity=".13">
      <rect x="624" y="348" width="200" height="9" rx="4.5"/>
      <rect x="624" y="370" width="150" height="9" rx="4.5"/>
    </g>
  </g>

  <!-- the leap -->
  <path d="M352 250 C430 20 570 20 640 286" fill="none" stroke="#ece8d8" stroke-opacity=".32"
        stroke-width="4" stroke-linecap="round" stroke-dasharray="2 14"/>

  <!-- the sprite, at 8x so every pixel stays square -->
  <g transform="translate(356 60) scale(8)" shape-rendering="crispEdges">
{rects(rows, '    ')}
  </g>
</svg>
'''


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    rows = sprite()
    for name, svg in (('graceful-mark.svg', mark(rows)),
                      ('graceful-agility.svg', banner(rows))):
        path = os.path.join(root, 'assets', name)
        with open(path, 'w') as f:
            f.write(svg)
        print(f'wrote {path}')


if __name__ == '__main__':
    main()
