name: graceful_panel
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  miracle:
    git:
      url: https://github.com/miracle-wm-org/miracle.dart.git
  wayland:
    git:
      url: https://github.com/robert-ancell/wayland.dart.git
  http: ^1.2.0
  udev: ^0.0.3
  dbus: ^0.7.11
  font_awesome_flutter: ^10.12.0
  pulseaudio: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
