// The evdev key codes miracle's key bindings are written in.
//
// `CustomKeyCommand.key` and `KeyCommandOverride.key` are raw Linux input event
// codes — `KEY_R` is 19 — so a binding editor that did not carry this table
// would be a numeric field asking the user to know `input-event-codes.h` by
// heart.
//
// Generated from `/usr/include/linux/input-event-codes.h` and then frozen: it is
// a kernel UAPI header, so a code that exists never changes meaning, and reading
// the host's copy at run time would make the same configuration render
// differently on two machines. Aliases (several spellings of one code) collapse
// to the first spelling the header gives, so the list is one row per code.
//
// Deliberately Flutter-free, like `input_trigger/keysym.dart`, so the lookups
// are a plain unit test.
library;

/// One key the compositor can bind, as evdev names it.
class MiracleKey {
  const MiracleKey(this.code, this.name, this.label);

  /// The Linux input event code — what miracle's configuration actually holds.
  final int code;

  /// The `input-event-codes.h` spelling, e.g. `KEY_LEFTBRACE`.
  ///
  /// Shown beside the label rather than instead of it: two keys can read alike
  /// once humanised ("Left bracket ([)" and "Keypad left paren"), and the
  /// header's own name is the unambiguous one to search for.
  final String name;

  /// What a person calls this key, e.g. `Left bracket ([)`.
  final String label;

  @override
  String toString() => 'MiracleKey($code, $name)';
}

/// Every key code evdev names, ascending.
const List<MiracleKey> kMiracleKeys = [
  MiracleKey(1, 'KEY_ESC', 'Escape'),
  MiracleKey(2, 'KEY_1', '1'),
  MiracleKey(3, 'KEY_2', '2'),
  MiracleKey(4, 'KEY_3', '3'),
  MiracleKey(5, 'KEY_4', '4'),
  MiracleKey(6, 'KEY_5', '5'),
  MiracleKey(7, 'KEY_6', '6'),
  MiracleKey(8, 'KEY_7', '7'),
  MiracleKey(9, 'KEY_8', '8'),
  MiracleKey(10, 'KEY_9', '9'),
  MiracleKey(11, 'KEY_0', '0'),
  MiracleKey(12, 'KEY_MINUS', 'Minus (-)'),
  MiracleKey(13, 'KEY_EQUAL', 'Equals (=)'),
  MiracleKey(14, 'KEY_BACKSPACE', 'Backspace'),
  MiracleKey(15, 'KEY_TAB', 'Tab'),
  MiracleKey(16, 'KEY_Q', 'Q'),
  MiracleKey(17, 'KEY_W', 'W'),
  MiracleKey(18, 'KEY_E', 'E'),
  MiracleKey(19, 'KEY_R', 'R'),
  MiracleKey(20, 'KEY_T', 'T'),
  MiracleKey(21, 'KEY_Y', 'Y'),
  MiracleKey(22, 'KEY_U', 'U'),
  MiracleKey(23, 'KEY_I', 'I'),
  MiracleKey(24, 'KEY_O', 'O'),
  MiracleKey(25, 'KEY_P', 'P'),
  MiracleKey(26, 'KEY_LEFTBRACE', 'Left bracket ([)'),
  MiracleKey(27, 'KEY_RIGHTBRACE', 'Right bracket (])'),
  MiracleKey(28, 'KEY_ENTER', 'Enter'),
  MiracleKey(29, 'KEY_LEFTCTRL', 'Left Ctrl'),
  MiracleKey(30, 'KEY_A', 'A'),
  MiracleKey(31, 'KEY_S', 'S'),
  MiracleKey(32, 'KEY_D', 'D'),
  MiracleKey(33, 'KEY_F', 'F'),
  MiracleKey(34, 'KEY_G', 'G'),
  MiracleKey(35, 'KEY_H', 'H'),
  MiracleKey(36, 'KEY_J', 'J'),
  MiracleKey(37, 'KEY_K', 'K'),
  MiracleKey(38, 'KEY_L', 'L'),
  MiracleKey(39, 'KEY_SEMICOLON', 'Semicolon (;)'),
  MiracleKey(40, 'KEY_APOSTROPHE', 'Apostrophe (\')'),
  MiracleKey(41, 'KEY_GRAVE', 'Grave (`)'),
  MiracleKey(42, 'KEY_LEFTSHIFT', 'Left Shift'),
  MiracleKey(43, 'KEY_BACKSLASH', 'Backslash (\\)'),
  MiracleKey(44, 'KEY_Z', 'Z'),
  MiracleKey(45, 'KEY_X', 'X'),
  MiracleKey(46, 'KEY_C', 'C'),
  MiracleKey(47, 'KEY_V', 'V'),
  MiracleKey(48, 'KEY_B', 'B'),
  MiracleKey(49, 'KEY_N', 'N'),
  MiracleKey(50, 'KEY_M', 'M'),
  MiracleKey(51, 'KEY_COMMA', 'Comma (,)'),
  MiracleKey(52, 'KEY_DOT', 'Period (.)'),
  MiracleKey(53, 'KEY_SLASH', 'Slash (/)'),
  MiracleKey(54, 'KEY_RIGHTSHIFT', 'Right Shift'),
  MiracleKey(55, 'KEY_KPASTERISK', 'Keypad asterisk (*)'),
  MiracleKey(56, 'KEY_LEFTALT', 'Left Alt'),
  MiracleKey(57, 'KEY_SPACE', 'Space'),
  MiracleKey(58, 'KEY_CAPSLOCK', 'Caps Lock'),
  MiracleKey(59, 'KEY_F1', 'F1'),
  MiracleKey(60, 'KEY_F2', 'F2'),
  MiracleKey(61, 'KEY_F3', 'F3'),
  MiracleKey(62, 'KEY_F4', 'F4'),
  MiracleKey(63, 'KEY_F5', 'F5'),
  MiracleKey(64, 'KEY_F6', 'F6'),
  MiracleKey(65, 'KEY_F7', 'F7'),
  MiracleKey(66, 'KEY_F8', 'F8'),
  MiracleKey(67, 'KEY_F9', 'F9'),
  MiracleKey(68, 'KEY_F10', 'F10'),
  MiracleKey(69, 'KEY_NUMLOCK', 'Num Lock'),
  MiracleKey(70, 'KEY_SCROLLLOCK', 'Scroll Lock'),
  MiracleKey(71, 'KEY_KP7', 'Keypad 7'),
  MiracleKey(72, 'KEY_KP8', 'Keypad 8'),
  MiracleKey(73, 'KEY_KP9', 'Keypad 9'),
  MiracleKey(74, 'KEY_KPMINUS', 'Keypad minus (-)'),
  MiracleKey(75, 'KEY_KP4', 'Keypad 4'),
  MiracleKey(76, 'KEY_KP5', 'Keypad 5'),
  MiracleKey(77, 'KEY_KP6', 'Keypad 6'),
  MiracleKey(78, 'KEY_KPPLUS', 'Keypad plus (+)'),
  MiracleKey(79, 'KEY_KP1', 'Keypad 1'),
  MiracleKey(80, 'KEY_KP2', 'Keypad 2'),
  MiracleKey(81, 'KEY_KP3', 'Keypad 3'),
  MiracleKey(82, 'KEY_KP0', 'Keypad 0'),
  MiracleKey(83, 'KEY_KPDOT', 'Keypad period (.)'),
  MiracleKey(85, 'KEY_ZENKAKUHANKAKU', 'Zenkakuhankaku'),
  MiracleKey(86, 'KEY_102ND', 'ISO extra key (102nd)'),
  MiracleKey(87, 'KEY_F11', 'F11'),
  MiracleKey(88, 'KEY_F12', 'F12'),
  MiracleKey(89, 'KEY_RO', 'Ro'),
  MiracleKey(90, 'KEY_KATAKANA', 'Katakana'),
  MiracleKey(91, 'KEY_HIRAGANA', 'Hiragana'),
  MiracleKey(92, 'KEY_HENKAN', 'Henkan'),
  MiracleKey(93, 'KEY_KATAKANAHIRAGANA', 'Katakanahiragana'),
  MiracleKey(94, 'KEY_MUHENKAN', 'Muhenkan'),
  MiracleKey(95, 'KEY_KPJPCOMMA', 'Keypad comma (JP)'),
  MiracleKey(96, 'KEY_KPENTER', 'Keypad Enter'),
  MiracleKey(97, 'KEY_RIGHTCTRL', 'Right Ctrl'),
  MiracleKey(98, 'KEY_KPSLASH', 'Keypad slash (/)'),
  MiracleKey(99, 'KEY_SYSRQ', 'Print Screen / SysRq'),
  MiracleKey(100, 'KEY_RIGHTALT', 'Right Alt'),
  MiracleKey(101, 'KEY_LINEFEED', 'Linefeed'),
  MiracleKey(102, 'KEY_HOME', 'Home'),
  MiracleKey(103, 'KEY_UP', 'Up arrow'),
  MiracleKey(104, 'KEY_PAGEUP', 'Page Up'),
  MiracleKey(105, 'KEY_LEFT', 'Left arrow'),
  MiracleKey(106, 'KEY_RIGHT', 'Right arrow'),
  MiracleKey(107, 'KEY_END', 'End'),
  MiracleKey(108, 'KEY_DOWN', 'Down arrow'),
  MiracleKey(109, 'KEY_PAGEDOWN', 'Page Down'),
  MiracleKey(110, 'KEY_INSERT', 'Insert'),
  MiracleKey(111, 'KEY_DELETE', 'Delete'),
  MiracleKey(112, 'KEY_MACRO', 'Macro'),
  MiracleKey(113, 'KEY_MUTE', 'Mute'),
  MiracleKey(114, 'KEY_VOLUMEDOWN', 'Volume down'),
  MiracleKey(115, 'KEY_VOLUMEUP', 'Volume up'),
  MiracleKey(116, 'KEY_POWER', 'Power'),
  MiracleKey(117, 'KEY_KPEQUAL', 'Keypad equals (=)'),
  MiracleKey(118, 'KEY_KPPLUSMINUS', 'Keypad plus/minus'),
  MiracleKey(119, 'KEY_PAUSE', 'Pause'),
  MiracleKey(120, 'KEY_SCALE', 'Scale'),
  MiracleKey(121, 'KEY_KPCOMMA', 'Keypad comma (,)'),
  MiracleKey(122, 'KEY_HANGEUL', 'Hangeul'),
  MiracleKey(123, 'KEY_HANJA', 'Hanja'),
  MiracleKey(124, 'KEY_YEN', 'Yen'),
  MiracleKey(125, 'KEY_LEFTMETA', 'Left Super'),
  MiracleKey(126, 'KEY_RIGHTMETA', 'Right Super'),
  MiracleKey(127, 'KEY_COMPOSE', 'Compose'),
  MiracleKey(128, 'KEY_STOP', 'Stop'),
  MiracleKey(129, 'KEY_AGAIN', 'Again'),
  MiracleKey(130, 'KEY_PROPS', 'Props'),
  MiracleKey(131, 'KEY_UNDO', 'Undo'),
  MiracleKey(132, 'KEY_FRONT', 'Front'),
  MiracleKey(133, 'KEY_COPY', 'Copy'),
  MiracleKey(134, 'KEY_OPEN', 'Open'),
  MiracleKey(135, 'KEY_PASTE', 'Paste'),
  MiracleKey(136, 'KEY_FIND', 'Find'),
  MiracleKey(137, 'KEY_CUT', 'Cut'),
  MiracleKey(138, 'KEY_HELP', 'Help'),
  MiracleKey(139, 'KEY_MENU', 'Menu'),
  MiracleKey(140, 'KEY_CALC', 'Calc'),
  MiracleKey(141, 'KEY_SETUP', 'Setup'),
  MiracleKey(142, 'KEY_SLEEP', 'Sleep'),
  MiracleKey(143, 'KEY_WAKEUP', 'Wakeup'),
  MiracleKey(144, 'KEY_FILE', 'File'),
  MiracleKey(145, 'KEY_SENDFILE', 'Sendfile'),
  MiracleKey(146, 'KEY_DELETEFILE', 'Deletefile'),
  MiracleKey(147, 'KEY_XFER', 'Xfer'),
  MiracleKey(148, 'KEY_PROG1', 'Prog1'),
  MiracleKey(149, 'KEY_PROG2', 'Prog2'),
  MiracleKey(150, 'KEY_WWW', 'Www'),
  MiracleKey(151, 'KEY_MSDOS', 'Msdos'),
  MiracleKey(152, 'KEY_COFFEE', 'Coffee'),
  MiracleKey(153, 'KEY_ROTATE_DISPLAY', 'Rotate Display'),
  MiracleKey(154, 'KEY_CYCLEWINDOWS', 'Cyclewindows'),
  MiracleKey(155, 'KEY_MAIL', 'Mail'),
  MiracleKey(156, 'KEY_BOOKMARKS', 'Bookmarks'),
  MiracleKey(157, 'KEY_COMPUTER', 'Computer'),
  MiracleKey(158, 'KEY_BACK', 'Back'),
  MiracleKey(159, 'KEY_FORWARD', 'Forward'),
  MiracleKey(160, 'KEY_CLOSECD', 'Closecd'),
  MiracleKey(161, 'KEY_EJECTCD', 'Ejectcd'),
  MiracleKey(162, 'KEY_EJECTCLOSECD', 'Ejectclosecd'),
  MiracleKey(163, 'KEY_NEXTSONG', 'Next track'),
  MiracleKey(164, 'KEY_PLAYPAUSE', 'Play/Pause'),
  MiracleKey(165, 'KEY_PREVIOUSSONG', 'Previous track'),
  MiracleKey(166, 'KEY_STOPCD', 'Stop (media)'),
  MiracleKey(167, 'KEY_RECORD', 'Record'),
  MiracleKey(168, 'KEY_REWIND', 'Rewind'),
  MiracleKey(169, 'KEY_PHONE', 'Phone'),
  MiracleKey(170, 'KEY_ISO', 'Iso'),
  MiracleKey(171, 'KEY_CONFIG', 'Config'),
  MiracleKey(172, 'KEY_HOMEPAGE', 'Homepage'),
  MiracleKey(173, 'KEY_REFRESH', 'Refresh'),
  MiracleKey(174, 'KEY_EXIT', 'Exit'),
  MiracleKey(175, 'KEY_MOVE', 'Move'),
  MiracleKey(176, 'KEY_EDIT', 'Edit'),
  MiracleKey(177, 'KEY_SCROLLUP', 'Scrollup'),
  MiracleKey(178, 'KEY_SCROLLDOWN', 'Scrolldown'),
  MiracleKey(179, 'KEY_KPLEFTPAREN', 'Keypad left paren'),
  MiracleKey(180, 'KEY_KPRIGHTPAREN', 'Keypad right paren'),
  MiracleKey(181, 'KEY_NEW', 'New'),
  MiracleKey(182, 'KEY_REDO', 'Redo'),
  MiracleKey(183, 'KEY_F13', 'F13'),
  MiracleKey(184, 'KEY_F14', 'F14'),
  MiracleKey(185, 'KEY_F15', 'F15'),
  MiracleKey(186, 'KEY_F16', 'F16'),
  MiracleKey(187, 'KEY_F17', 'F17'),
  MiracleKey(188, 'KEY_F18', 'F18'),
  MiracleKey(189, 'KEY_F19', 'F19'),
  MiracleKey(190, 'KEY_F20', 'F20'),
  MiracleKey(191, 'KEY_F21', 'F21'),
  MiracleKey(192, 'KEY_F22', 'F22'),
  MiracleKey(193, 'KEY_F23', 'F23'),
  MiracleKey(194, 'KEY_F24', 'F24'),
  MiracleKey(200, 'KEY_PLAYCD', 'Playcd'),
  MiracleKey(201, 'KEY_PAUSECD', 'Pausecd'),
  MiracleKey(202, 'KEY_PROG3', 'Prog3'),
  MiracleKey(203, 'KEY_PROG4', 'Prog4'),
  MiracleKey(204, 'KEY_ALL_APPLICATIONS', 'All Applications'),
  MiracleKey(205, 'KEY_SUSPEND', 'Suspend'),
  MiracleKey(206, 'KEY_CLOSE', 'Close'),
  MiracleKey(207, 'KEY_PLAY', 'Play'),
  MiracleKey(208, 'KEY_FASTFORWARD', 'Fastforward'),
  MiracleKey(209, 'KEY_BASSBOOST', 'Bassboost'),
  MiracleKey(210, 'KEY_PRINT', 'Print'),
  MiracleKey(211, 'KEY_HP', 'Hp'),
  MiracleKey(212, 'KEY_CAMERA', 'Camera'),
  MiracleKey(213, 'KEY_SOUND', 'Sound'),
  MiracleKey(214, 'KEY_QUESTION', 'Question'),
  MiracleKey(215, 'KEY_EMAIL', 'Email'),
  MiracleKey(216, 'KEY_CHAT', 'Chat'),
  MiracleKey(217, 'KEY_SEARCH', 'Search'),
  MiracleKey(218, 'KEY_CONNECT', 'Connect'),
  MiracleKey(219, 'KEY_FINANCE', 'Finance'),
  MiracleKey(220, 'KEY_SPORT', 'Sport'),
  MiracleKey(221, 'KEY_SHOP', 'Shop'),
  MiracleKey(222, 'KEY_ALTERASE', 'Alterase'),
  MiracleKey(223, 'KEY_CANCEL', 'Cancel'),
  MiracleKey(224, 'KEY_BRIGHTNESSDOWN', 'Brightness down'),
  MiracleKey(225, 'KEY_BRIGHTNESSUP', 'Brightness up'),
  MiracleKey(226, 'KEY_MEDIA', 'Media'),
  MiracleKey(227, 'KEY_SWITCHVIDEOMODE', 'Switchvideomode'),
  MiracleKey(228, 'KEY_KBDILLUMTOGGLE', 'Kbdillumtoggle'),
  MiracleKey(229, 'KEY_KBDILLUMDOWN', 'Kbdillumdown'),
  MiracleKey(230, 'KEY_KBDILLUMUP', 'Kbdillumup'),
  MiracleKey(231, 'KEY_SEND', 'Send'),
  MiracleKey(232, 'KEY_REPLY', 'Reply'),
  MiracleKey(233, 'KEY_FORWARDMAIL', 'Forwardmail'),
  MiracleKey(234, 'KEY_SAVE', 'Save'),
  MiracleKey(235, 'KEY_DOCUMENTS', 'Documents'),
  MiracleKey(236, 'KEY_BATTERY', 'Battery'),
  MiracleKey(237, 'KEY_BLUETOOTH', 'Bluetooth'),
  MiracleKey(238, 'KEY_WLAN', 'Wlan'),
  MiracleKey(239, 'KEY_UWB', 'Uwb'),
  MiracleKey(240, 'KEY_UNKNOWN', 'Unknown'),
  MiracleKey(241, 'KEY_VIDEO_NEXT', 'Video Next'),
  MiracleKey(242, 'KEY_VIDEO_PREV', 'Video Prev'),
  MiracleKey(243, 'KEY_BRIGHTNESS_CYCLE', 'Brightness Cycle'),
  MiracleKey(244, 'KEY_BRIGHTNESS_AUTO', 'Brightness Auto'),
  MiracleKey(245, 'KEY_DISPLAY_OFF', 'Display Off'),
  MiracleKey(246, 'KEY_WWAN', 'Wwan'),
  MiracleKey(247, 'KEY_RFKILL', 'Rfkill'),
  MiracleKey(248, 'KEY_MICMUTE', 'Micmute'),
  MiracleKey(352, 'KEY_OK', 'Ok'),
  MiracleKey(353, 'KEY_SELECT', 'Select'),
  MiracleKey(354, 'KEY_GOTO', 'Goto'),
  MiracleKey(355, 'KEY_CLEAR', 'Clear'),
  MiracleKey(356, 'KEY_POWER2', 'Power2'),
  MiracleKey(357, 'KEY_OPTION', 'Option'),
  MiracleKey(358, 'KEY_INFO', 'Info'),
  MiracleKey(359, 'KEY_TIME', 'Time'),
  MiracleKey(360, 'KEY_VENDOR', 'Vendor'),
  MiracleKey(361, 'KEY_ARCHIVE', 'Archive'),
  MiracleKey(362, 'KEY_PROGRAM', 'Program'),
  MiracleKey(363, 'KEY_CHANNEL', 'Channel'),
  MiracleKey(364, 'KEY_FAVORITES', 'Favorites'),
  MiracleKey(365, 'KEY_EPG', 'Epg'),
  MiracleKey(366, 'KEY_PVR', 'Pvr'),
  MiracleKey(367, 'KEY_MHP', 'Mhp'),
  MiracleKey(368, 'KEY_LANGUAGE', 'Language'),
  MiracleKey(369, 'KEY_TITLE', 'Title'),
  MiracleKey(370, 'KEY_SUBTITLE', 'Subtitle'),
  MiracleKey(371, 'KEY_ANGLE', 'Angle'),
  MiracleKey(372, 'KEY_FULL_SCREEN', 'Full Screen'),
  MiracleKey(373, 'KEY_MODE', 'Mode'),
  MiracleKey(374, 'KEY_KEYBOARD', 'Keyboard'),
  MiracleKey(375, 'KEY_ASPECT_RATIO', 'Aspect Ratio'),
  MiracleKey(376, 'KEY_PC', 'Pc'),
  MiracleKey(377, 'KEY_TV', 'Tv'),
  MiracleKey(378, 'KEY_TV2', 'Tv2'),
  MiracleKey(379, 'KEY_VCR', 'Vcr'),
  MiracleKey(380, 'KEY_VCR2', 'Vcr2'),
  MiracleKey(381, 'KEY_SAT', 'Sat'),
  MiracleKey(382, 'KEY_SAT2', 'Sat2'),
  MiracleKey(383, 'KEY_CD', 'Cd'),
  MiracleKey(384, 'KEY_TAPE', 'Tape'),
  MiracleKey(385, 'KEY_RADIO', 'Radio'),
  MiracleKey(386, 'KEY_TUNER', 'Tuner'),
  MiracleKey(387, 'KEY_PLAYER', 'Player'),
  MiracleKey(388, 'KEY_TEXT', 'Text'),
  MiracleKey(389, 'KEY_DVD', 'Dvd'),
  MiracleKey(390, 'KEY_AUX', 'Aux'),
  MiracleKey(391, 'KEY_MP3', 'Mp3'),
  MiracleKey(392, 'KEY_AUDIO', 'Audio'),
  MiracleKey(393, 'KEY_VIDEO', 'Video'),
  MiracleKey(394, 'KEY_DIRECTORY', 'Directory'),
  MiracleKey(395, 'KEY_LIST', 'List'),
  MiracleKey(396, 'KEY_MEMO', 'Memo'),
  MiracleKey(397, 'KEY_CALENDAR', 'Calendar'),
  MiracleKey(398, 'KEY_RED', 'Red'),
  MiracleKey(399, 'KEY_GREEN', 'Green'),
  MiracleKey(400, 'KEY_YELLOW', 'Yellow'),
  MiracleKey(401, 'KEY_BLUE', 'Blue'),
  MiracleKey(402, 'KEY_CHANNELUP', 'Channelup'),
  MiracleKey(403, 'KEY_CHANNELDOWN', 'Channeldown'),
  MiracleKey(404, 'KEY_FIRST', 'First'),
  MiracleKey(405, 'KEY_LAST', 'Last'),
  MiracleKey(406, 'KEY_AB', 'Ab'),
  MiracleKey(407, 'KEY_NEXT', 'Next'),
  MiracleKey(408, 'KEY_RESTART', 'Restart'),
  MiracleKey(409, 'KEY_SLOW', 'Slow'),
  MiracleKey(410, 'KEY_SHUFFLE', 'Shuffle'),
  MiracleKey(411, 'KEY_BREAK', 'Break'),
  MiracleKey(412, 'KEY_PREVIOUS', 'Previous'),
  MiracleKey(413, 'KEY_DIGITS', 'Digits'),
  MiracleKey(414, 'KEY_TEEN', 'Teen'),
  MiracleKey(415, 'KEY_TWEN', 'Twen'),
  MiracleKey(416, 'KEY_VIDEOPHONE', 'Videophone'),
  MiracleKey(417, 'KEY_GAMES', 'Games'),
  MiracleKey(418, 'KEY_ZOOMIN', 'Zoomin'),
  MiracleKey(419, 'KEY_ZOOMOUT', 'Zoomout'),
  MiracleKey(420, 'KEY_ZOOMRESET', 'Zoomreset'),
  MiracleKey(421, 'KEY_WORDPROCESSOR', 'Wordprocessor'),
  MiracleKey(422, 'KEY_EDITOR', 'Editor'),
  MiracleKey(423, 'KEY_SPREADSHEET', 'Spreadsheet'),
  MiracleKey(424, 'KEY_GRAPHICSEDITOR', 'Graphicseditor'),
  MiracleKey(425, 'KEY_PRESENTATION', 'Presentation'),
  MiracleKey(426, 'KEY_DATABASE', 'Database'),
  MiracleKey(427, 'KEY_NEWS', 'News'),
  MiracleKey(428, 'KEY_VOICEMAIL', 'Voicemail'),
  MiracleKey(429, 'KEY_ADDRESSBOOK', 'Addressbook'),
  MiracleKey(430, 'KEY_MESSENGER', 'Messenger'),
  MiracleKey(431, 'KEY_DISPLAYTOGGLE', 'Displaytoggle'),
  MiracleKey(432, 'KEY_SPELLCHECK', 'Spellcheck'),
  MiracleKey(433, 'KEY_LOGOFF', 'Logoff'),
  MiracleKey(434, 'KEY_DOLLAR', 'Dollar'),
  MiracleKey(435, 'KEY_EURO', 'Euro'),
  MiracleKey(436, 'KEY_FRAMEBACK', 'Frameback'),
  MiracleKey(437, 'KEY_FRAMEFORWARD', 'Frameforward'),
  MiracleKey(438, 'KEY_CONTEXT_MENU', 'Context Menu'),
  MiracleKey(439, 'KEY_MEDIA_REPEAT', 'Media Repeat'),
  MiracleKey(440, 'KEY_10CHANNELSUP', '10channelsup'),
  MiracleKey(441, 'KEY_10CHANNELSDOWN', '10channelsdown'),
  MiracleKey(442, 'KEY_IMAGES', 'Images'),
  MiracleKey(444, 'KEY_NOTIFICATION_CENTER', 'Notification Center'),
  MiracleKey(445, 'KEY_PICKUP_PHONE', 'Pickup Phone'),
  MiracleKey(446, 'KEY_HANGUP_PHONE', 'Hangup Phone'),
  MiracleKey(447, 'KEY_LINK_PHONE', 'Link Phone'),
  MiracleKey(448, 'KEY_DEL_EOL', 'Del Eol'),
  MiracleKey(449, 'KEY_DEL_EOS', 'Del Eos'),
  MiracleKey(450, 'KEY_INS_LINE', 'Ins Line'),
  MiracleKey(451, 'KEY_DEL_LINE', 'Del Line'),
  MiracleKey(464, 'KEY_FN', 'Fn'),
  MiracleKey(465, 'KEY_FN_ESC', 'Fn Esc'),
  MiracleKey(466, 'KEY_FN_F1', 'Fn F1'),
  MiracleKey(467, 'KEY_FN_F2', 'Fn F2'),
  MiracleKey(468, 'KEY_FN_F3', 'Fn F3'),
  MiracleKey(469, 'KEY_FN_F4', 'Fn F4'),
  MiracleKey(470, 'KEY_FN_F5', 'Fn F5'),
  MiracleKey(471, 'KEY_FN_F6', 'Fn F6'),
  MiracleKey(472, 'KEY_FN_F7', 'Fn F7'),
  MiracleKey(473, 'KEY_FN_F8', 'Fn F8'),
  MiracleKey(474, 'KEY_FN_F9', 'Fn F9'),
  MiracleKey(475, 'KEY_FN_F10', 'Fn F10'),
  MiracleKey(476, 'KEY_FN_F11', 'Fn F11'),
  MiracleKey(477, 'KEY_FN_F12', 'Fn F12'),
  MiracleKey(478, 'KEY_FN_1', 'Fn 1'),
  MiracleKey(479, 'KEY_FN_2', 'Fn 2'),
  MiracleKey(480, 'KEY_FN_D', 'Fn D'),
  MiracleKey(481, 'KEY_FN_E', 'Fn E'),
  MiracleKey(482, 'KEY_FN_F', 'Fn F'),
  MiracleKey(483, 'KEY_FN_S', 'Fn S'),
  MiracleKey(484, 'KEY_FN_B', 'Fn B'),
  MiracleKey(485, 'KEY_FN_RIGHT_SHIFT', 'Fn Right Shift'),
  MiracleKey(497, 'KEY_BRL_DOT1', 'Brl Dot1'),
  MiracleKey(498, 'KEY_BRL_DOT2', 'Brl Dot2'),
  MiracleKey(499, 'KEY_BRL_DOT3', 'Brl Dot3'),
  MiracleKey(500, 'KEY_BRL_DOT4', 'Brl Dot4'),
  MiracleKey(501, 'KEY_BRL_DOT5', 'Brl Dot5'),
  MiracleKey(502, 'KEY_BRL_DOT6', 'Brl Dot6'),
  MiracleKey(503, 'KEY_BRL_DOT7', 'Brl Dot7'),
  MiracleKey(504, 'KEY_BRL_DOT8', 'Brl Dot8'),
  MiracleKey(505, 'KEY_BRL_DOT9', 'Brl Dot9'),
  MiracleKey(506, 'KEY_BRL_DOT10', 'Brl Dot10'),
  MiracleKey(512, 'KEY_NUMERIC_0', 'Numeric 0'),
  MiracleKey(513, 'KEY_NUMERIC_1', 'Numeric 1'),
  MiracleKey(514, 'KEY_NUMERIC_2', 'Numeric 2'),
  MiracleKey(515, 'KEY_NUMERIC_3', 'Numeric 3'),
  MiracleKey(516, 'KEY_NUMERIC_4', 'Numeric 4'),
  MiracleKey(517, 'KEY_NUMERIC_5', 'Numeric 5'),
  MiracleKey(518, 'KEY_NUMERIC_6', 'Numeric 6'),
  MiracleKey(519, 'KEY_NUMERIC_7', 'Numeric 7'),
  MiracleKey(520, 'KEY_NUMERIC_8', 'Numeric 8'),
  MiracleKey(521, 'KEY_NUMERIC_9', 'Numeric 9'),
  MiracleKey(522, 'KEY_NUMERIC_STAR', 'Numeric Star'),
  MiracleKey(523, 'KEY_NUMERIC_POUND', 'Numeric Pound'),
  MiracleKey(524, 'KEY_NUMERIC_A', 'Numeric A'),
  MiracleKey(525, 'KEY_NUMERIC_B', 'Numeric B'),
  MiracleKey(526, 'KEY_NUMERIC_C', 'Numeric C'),
  MiracleKey(527, 'KEY_NUMERIC_D', 'Numeric D'),
  MiracleKey(528, 'KEY_CAMERA_FOCUS', 'Camera Focus'),
  MiracleKey(529, 'KEY_WPS_BUTTON', 'Wps Button'),
  MiracleKey(530, 'KEY_TOUCHPAD_TOGGLE', 'Touchpad Toggle'),
  MiracleKey(531, 'KEY_TOUCHPAD_ON', 'Touchpad On'),
  MiracleKey(532, 'KEY_TOUCHPAD_OFF', 'Touchpad Off'),
  MiracleKey(533, 'KEY_CAMERA_ZOOMIN', 'Camera Zoomin'),
  MiracleKey(534, 'KEY_CAMERA_ZOOMOUT', 'Camera Zoomout'),
  MiracleKey(535, 'KEY_CAMERA_UP', 'Camera Up'),
  MiracleKey(536, 'KEY_CAMERA_DOWN', 'Camera Down'),
  MiracleKey(537, 'KEY_CAMERA_LEFT', 'Camera Left'),
  MiracleKey(538, 'KEY_CAMERA_RIGHT', 'Camera Right'),
  MiracleKey(539, 'KEY_ATTENDANT_ON', 'Attendant On'),
  MiracleKey(540, 'KEY_ATTENDANT_OFF', 'Attendant Off'),
  MiracleKey(541, 'KEY_ATTENDANT_TOGGLE', 'Attendant Toggle'),
  MiracleKey(542, 'KEY_LIGHTS_TOGGLE', 'Lights Toggle'),
  MiracleKey(560, 'KEY_ALS_TOGGLE', 'Als Toggle'),
  MiracleKey(561, 'KEY_ROTATE_LOCK_TOGGLE', 'Rotate Lock Toggle'),
  MiracleKey(562, 'KEY_REFRESH_RATE_TOGGLE', 'Refresh Rate Toggle'),
  MiracleKey(576, 'KEY_BUTTONCONFIG', 'Buttonconfig'),
  MiracleKey(577, 'KEY_TASKMANAGER', 'Taskmanager'),
  MiracleKey(578, 'KEY_JOURNAL', 'Journal'),
  MiracleKey(579, 'KEY_CONTROLPANEL', 'Controlpanel'),
  MiracleKey(580, 'KEY_APPSELECT', 'Appselect'),
  MiracleKey(581, 'KEY_SCREENSAVER', 'Screensaver'),
  MiracleKey(582, 'KEY_VOICECOMMAND', 'Voicecommand'),
  MiracleKey(583, 'KEY_ASSISTANT', 'Assistant'),
  MiracleKey(584, 'KEY_KBD_LAYOUT_NEXT', 'Kbd Layout Next'),
  MiracleKey(585, 'KEY_EMOJI_PICKER', 'Emoji Picker'),
  MiracleKey(586, 'KEY_DICTATE', 'Dictate'),
  MiracleKey(587, 'KEY_CAMERA_ACCESS_ENABLE', 'Camera Access Enable'),
  MiracleKey(588, 'KEY_CAMERA_ACCESS_DISABLE', 'Camera Access Disable'),
  MiracleKey(589, 'KEY_CAMERA_ACCESS_TOGGLE', 'Camera Access Toggle'),
  MiracleKey(590, 'KEY_ACCESSIBILITY', 'Accessibility'),
  MiracleKey(591, 'KEY_DO_NOT_DISTURB', 'Do Not Disturb'),
  MiracleKey(592, 'KEY_BRIGHTNESS_MIN', 'Brightness Min'),
  MiracleKey(593, 'KEY_BRIGHTNESS_MAX', 'Brightness Max'),
  MiracleKey(608, 'KEY_KBDINPUTASSIST_PREV', 'Kbdinputassist Prev'),
  MiracleKey(609, 'KEY_KBDINPUTASSIST_NEXT', 'Kbdinputassist Next'),
  MiracleKey(610, 'KEY_KBDINPUTASSIST_PREVGROUP', 'Kbdinputassist Prevgroup'),
  MiracleKey(611, 'KEY_KBDINPUTASSIST_NEXTGROUP', 'Kbdinputassist Nextgroup'),
  MiracleKey(612, 'KEY_KBDINPUTASSIST_ACCEPT', 'Kbdinputassist Accept'),
  MiracleKey(613, 'KEY_KBDINPUTASSIST_CANCEL', 'Kbdinputassist Cancel'),
  MiracleKey(614, 'KEY_RIGHT_UP', 'Right Up'),
  MiracleKey(615, 'KEY_RIGHT_DOWN', 'Right Down'),
  MiracleKey(616, 'KEY_LEFT_UP', 'Left Up'),
  MiracleKey(617, 'KEY_LEFT_DOWN', 'Left Down'),
  MiracleKey(618, 'KEY_ROOT_MENU', 'Root Menu'),
  MiracleKey(619, 'KEY_MEDIA_TOP_MENU', 'Media Top Menu'),
  MiracleKey(620, 'KEY_NUMERIC_11', 'Numeric 11'),
  MiracleKey(621, 'KEY_NUMERIC_12', 'Numeric 12'),
  MiracleKey(622, 'KEY_AUDIO_DESC', 'Audio Desc'),
  MiracleKey(623, 'KEY_3D_MODE', '3d Mode'),
  MiracleKey(624, 'KEY_NEXT_FAVORITE', 'Next Favorite'),
  MiracleKey(625, 'KEY_STOP_RECORD', 'Stop Record'),
  MiracleKey(626, 'KEY_PAUSE_RECORD', 'Pause Record'),
  MiracleKey(627, 'KEY_VOD', 'Vod'),
  MiracleKey(628, 'KEY_UNMUTE', 'Unmute'),
  MiracleKey(629, 'KEY_FASTREVERSE', 'Fastreverse'),
  MiracleKey(630, 'KEY_SLOWREVERSE', 'Slowreverse'),
  MiracleKey(631, 'KEY_DATA', 'Data'),
  MiracleKey(632, 'KEY_ONSCREEN_KEYBOARD', 'Onscreen Keyboard'),
  MiracleKey(633, 'KEY_PRIVACY_SCREEN_TOGGLE', 'Privacy Screen Toggle'),
  MiracleKey(634, 'KEY_SELECTIVE_SCREENSHOT', 'Selective Screenshot'),
  MiracleKey(635, 'KEY_NEXT_ELEMENT', 'Next Element'),
  MiracleKey(636, 'KEY_PREVIOUS_ELEMENT', 'Previous Element'),
  MiracleKey(637, 'KEY_AUTOPILOT_ENGAGE_TOGGLE', 'Autopilot Engage Toggle'),
  MiracleKey(638, 'KEY_MARK_WAYPOINT', 'Mark Waypoint'),
  MiracleKey(639, 'KEY_SOS', 'Sos'),
  MiracleKey(640, 'KEY_NAV_CHART', 'Nav Chart'),
  MiracleKey(641, 'KEY_FISHING_CHART', 'Fishing Chart'),
  MiracleKey(642, 'KEY_SINGLE_RANGE_RADAR', 'Single Range Radar'),
  MiracleKey(643, 'KEY_DUAL_RANGE_RADAR', 'Dual Range Radar'),
  MiracleKey(644, 'KEY_RADAR_OVERLAY', 'Radar Overlay'),
  MiracleKey(645, 'KEY_TRADITIONAL_SONAR', 'Traditional Sonar'),
  MiracleKey(646, 'KEY_CLEARVU_SONAR', 'Clearvu Sonar'),
  MiracleKey(647, 'KEY_SIDEVU_SONAR', 'Sidevu Sonar'),
  MiracleKey(648, 'KEY_NAV_INFO', 'Nav Info'),
  MiracleKey(649, 'KEY_BRIGHTNESS_MENU', 'Brightness Menu'),
  MiracleKey(656, 'KEY_MACRO1', 'Macro1'),
  MiracleKey(657, 'KEY_MACRO2', 'Macro2'),
  MiracleKey(658, 'KEY_MACRO3', 'Macro3'),
  MiracleKey(659, 'KEY_MACRO4', 'Macro4'),
  MiracleKey(660, 'KEY_MACRO5', 'Macro5'),
  MiracleKey(661, 'KEY_MACRO6', 'Macro6'),
  MiracleKey(662, 'KEY_MACRO7', 'Macro7'),
  MiracleKey(663, 'KEY_MACRO8', 'Macro8'),
  MiracleKey(664, 'KEY_MACRO9', 'Macro9'),
  MiracleKey(665, 'KEY_MACRO10', 'Macro10'),
  MiracleKey(666, 'KEY_MACRO11', 'Macro11'),
  MiracleKey(667, 'KEY_MACRO12', 'Macro12'),
  MiracleKey(668, 'KEY_MACRO13', 'Macro13'),
  MiracleKey(669, 'KEY_MACRO14', 'Macro14'),
  MiracleKey(670, 'KEY_MACRO15', 'Macro15'),
  MiracleKey(671, 'KEY_MACRO16', 'Macro16'),
  MiracleKey(672, 'KEY_MACRO17', 'Macro17'),
  MiracleKey(673, 'KEY_MACRO18', 'Macro18'),
  MiracleKey(674, 'KEY_MACRO19', 'Macro19'),
  MiracleKey(675, 'KEY_MACRO20', 'Macro20'),
  MiracleKey(676, 'KEY_MACRO21', 'Macro21'),
  MiracleKey(677, 'KEY_MACRO22', 'Macro22'),
  MiracleKey(678, 'KEY_MACRO23', 'Macro23'),
  MiracleKey(679, 'KEY_MACRO24', 'Macro24'),
  MiracleKey(680, 'KEY_MACRO25', 'Macro25'),
  MiracleKey(681, 'KEY_MACRO26', 'Macro26'),
  MiracleKey(682, 'KEY_MACRO27', 'Macro27'),
  MiracleKey(683, 'KEY_MACRO28', 'Macro28'),
  MiracleKey(684, 'KEY_MACRO29', 'Macro29'),
  MiracleKey(685, 'KEY_MACRO30', 'Macro30'),
  MiracleKey(688, 'KEY_MACRO_RECORD_START', 'Macro Record Start'),
  MiracleKey(689, 'KEY_MACRO_RECORD_STOP', 'Macro Record Stop'),
  MiracleKey(690, 'KEY_MACRO_PRESET_CYCLE', 'Macro Preset Cycle'),
  MiracleKey(691, 'KEY_MACRO_PRESET1', 'Macro Preset1'),
  MiracleKey(692, 'KEY_MACRO_PRESET2', 'Macro Preset2'),
  MiracleKey(693, 'KEY_MACRO_PRESET3', 'Macro Preset3'),
  MiracleKey(696, 'KEY_KBD_LCD_MENU1', 'Kbd Lcd Menu1'),
  MiracleKey(697, 'KEY_KBD_LCD_MENU2', 'Kbd Lcd Menu2'),
  MiracleKey(698, 'KEY_KBD_LCD_MENU3', 'Kbd Lcd Menu3'),
  MiracleKey(699, 'KEY_KBD_LCD_MENU4', 'Kbd Lcd Menu4'),
  MiracleKey(700, 'KEY_KBD_LCD_MENU5', 'Kbd Lcd Menu5'),
];

/// The table, indexed for lookup.
///
/// Lazy: a shell whose user never opens the key bindings page builds none of it
/// — `world_cities.dart`'s trick.
final Map<int, MiracleKey> _byCode = {
  for (final key in kMiracleKeys) key.code: key,
};

/// The key [code] names, or null if evdev does not name it.
MiracleKey? miracleKeyForCode(int code) => _byCode[code];

/// A label for [code], falling back to the number itself.
///
/// A binding can perfectly well name a code this table does not — a vendor key
/// on somebody's keyboard, or a configuration written against a newer kernel —
/// and showing it as "Key code 748" keeps that binding editable and, above all,
/// *saveable* as it was authored. The degrade-per-field rule from
/// `config_reader.dart`, applied to somebody else's file.
String miracleKeyLabel(int code) => _byCode[code]?.label ?? 'Key code $code';
